//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public employees()
        {
            this.departments1 = new HashSet<departments>();
            this.users = new HashSet<users>();
            this.vacation_requests = new HashSet<vacation_requests>();
            this.vacation_requests1 = new HashSet<vacation_requests>();
        }
    
        public int employee_id { get; set; }
        public string full_name { get; set; }
        public int position_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public System.DateTime hire_date { get; set; }
        public decimal salary { get; set; }
        public string work_schedule { get; set; }
    
        public virtual departments departments { get; set; }
        public virtual ICollection<departments> departments1 { get; set; }
        public virtual positions positions { get; set; }
        public virtual ICollection<users> users { get; set; }
        public virtual ICollection<vacation_requests> vacation_requests { get; set; }
        public virtual ICollection<vacation_requests> vacation_requests1 { get; set; }
    }
}
