//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KadryAdministratsiEntities : DbContext
    {
        public KadryAdministratsiEntities()
            : base("name=KadryAdministratsiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<departments> departments { get; set; }
        public DbSet<employees> employees { get; set; }
        public DbSet<positions> positions { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<vacation_requests> vacation_requests { get; set; }
    }
}
