//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class positions
    {
        public positions()
        {
            this.employees = new HashSet<employees>();
        }
    
        public int position_id { get; set; }
        public string title { get; set; }
        public byte access_level { get; set; }
    
        public virtual ICollection<employees> employees { get; set; }
    }
}
